#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/xray run -c /etc/xray/router.json
    procd_set_param respawn
    procd_close_instance
}

