#!/bin/sh

set -e

set_xray_routing() {
    # Make the xray0 interface visible to netifd and steer default traffic to it.
    uci -q delete network.xray
    uci -q set network.xray='interface'
    uci -q set network.xray.proto='none'
    uci -q set network.xray.device='xray0'

    uci -q add network route
    uci -q set network.@route[-1].interface='xray'
    uci -q set network.@route[-1].target='0.0.0.0'
    uci -q set network.@route[-1].netmask='0.0.0.0'
    uci -q set network.@route[-1].metric='1'

    uci -q add network route6
    uci -q set network.@route6[-1].interface='xray'
    uci -q set network.@route6[-1].target='::/0'
    uci -q set network.@route6[-1].metric='1'

    uci -q commit network
}

set_xray_routing

/etc/init.d/xray enable
exit 0
